#!/usr/bin/env bash
# =============================================================================
# build.sh — Yocto build orchestrator for Jetson Orin Nano BSP
# =============================================================================
# Wraps `kas build` with runtime flags for CPU allocation, rootfs mode,
# and dm-verity toggle. Generates a temporary kas override YAML that is
# merged with the base kas-project.yml at build time.
#
# Usage:
#   ./build.sh [OPTIONS] [-- EXTRA_KAS_ARGS]
#
# Examples:
#   ./build.sh --cores 8 --rootfs ro --dm-verity               # production
#   ./build.sh --cores 4 --rootfs overlayfs --dm-verity         # field debug
#   ./build.sh --rootfs rw --no-dm-verity                       # dev iteration
#   ./build.sh --cpu-affinity 0-3 --cores 4                     # pinned build
#   ./build.sh --cores 4 --target demo-image-base -c populate_sdk  # build SDK
# =============================================================================
set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Auto-activate the project venv if kas isn't already on PATH
if ! command -v kas >/dev/null 2>&1 && [[ -f "${SCRIPT_DIR}/.venv/bin/activate" ]]; then
    # shellcheck source=/dev/null
    source "${SCRIPT_DIR}/.venv/bin/activate"
fi

KAS_BASE="${SCRIPT_DIR}/kas-project.yml"
CORES=""
CPU_AFFINITY=""
ROOTFS_MODE="ro"         # ro | rw | overlayfs
DM_VERITY="on"           # on | off
TARGET=""
EXTRA_KAS_ARGS=()

# ── Color helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[FATAL]${NC} $*" >&2; exit 1; }

# ── Usage ────────────────────────────────────────────────────────────────────
usage() {
    cat <<'EOF'
Usage: ./build.sh [OPTIONS] [-- EXTRA_KAS_ARGS]

Options:
  -c, --cores N            Number of CPU cores for BB_NUMBER_THREADS / PARALLEL_MAKE
                           (default: 80% of available cores)
  -a, --cpu-affinity MASK  CPU affinity mask for taskset (e.g., 0-7 or 0,2,4,6)
  -r, --rootfs MODE        Rootfs mode: ro | rw | overlayfs  (default: ro)
  -d, --dm-verity          Enable dm-verity signing  (default)
      --no-dm-verity       Disable dm-verity signing
  -t, --target IMAGE       Override bitbake target (default: from kas-project.yml)
  -h, --help               Show this help

Extra arguments after -- are passed directly to kas, e.g.:
  ./build.sh -- --cmd "bitbake -n demo-image-base"
EOF
    exit 0
}

# ── Argument parsing ─────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        -c|--cores)        CORES="$2"; shift 2 ;;
        -a|--cpu-affinity) CPU_AFFINITY="$2"; shift 2 ;;
        -r|--rootfs)       ROOTFS_MODE="$2"; shift 2 ;;
        -d|--dm-verity)    DM_VERITY="on"; shift ;;
        --no-dm-verity)    DM_VERITY="off"; shift ;;
        -t|--target)       TARGET="$2"; shift 2 ;;
        -h|--help)         usage ;;
        --)                shift; EXTRA_KAS_ARGS=("$@"); break ;;
        *)                 die "Unknown option: $1  (use -h for help)" ;;
    esac
done

# ── Validate inputs ──────────────────────────────────────────────────────────
[[ "$ROOTFS_MODE" =~ ^(ro|rw|overlayfs)$ ]] || die "Invalid --rootfs mode: $ROOTFS_MODE (must be ro|rw|overlayfs)"
command -v kas >/dev/null 2>&1 || die "kas not found. Install: pip install kas"

if [[ "$DM_VERITY" == "on" ]]; then
    KEY="${SCRIPT_DIR}/keys/dm-verity/rsa3k-key.pem"
    CERT="${SCRIPT_DIR}/keys/dm-verity/rsa3k-cert.pem"
    [[ -f "$KEY" ]]  || die "dm-verity signing key not found: $KEY\n  Generate with: ./build.sh --help  (see README.md § DM-Verity Signing)"
    [[ -f "$CERT" ]] || die "dm-verity signing cert not found: $CERT"
fi

# ── Compute core count ───────────────────────────────────────────────────────
TOTAL_CORES=$(nproc)
if [[ -z "$CORES" ]]; then
    CORES=$(( TOTAL_CORES * 80 / 100 ))
    [[ "$CORES" -lt 1 ]] && CORES=1
fi
info "Build parallelism: ${CORES} threads (of ${TOTAL_CORES} available)"

# ── Generate kas override YAML ───────────────────────────────────────────────
# kas 5.2+ requires all concatenated configs to live in the same repo.
# Write the override under SCRIPT_DIR/tmp/ which is gitignored.
mkdir -p "${SCRIPT_DIR}/tmp"
OVERRIDE_FILE=$(mktemp "${SCRIPT_DIR}/tmp/kas-override-XXXXXX.yml")
trap 'rm -f "$OVERRIDE_FILE"' EXIT

cat > "$OVERRIDE_FILE" <<YAML
# Auto-generated by build.sh — $(date -Iseconds)
# DO NOT EDIT — this file is regenerated on every build invocation.
header:
  version: 14

local_conf_header:
  build-sh-cores: |
    BB_NUMBER_THREADS = "${CORES}"
    PARALLEL_MAKE = "-j ${CORES}"
YAML

# ── Rootfs mode injection ────────────────────────────────────────────────────
case "$ROOTFS_MODE" in
    ro)
        info "Rootfs mode: read-only (hardened)"
        cat >> "$OVERRIDE_FILE" <<'YAML'
  build-sh-rootfs: |
    IMAGE_FEATURES:append = " read-only-rootfs"
YAML
        ;;
    rw)
        warn "Rootfs mode: read-write (development only — NOT for production)"
        cat >> "$OVERRIDE_FILE" <<'YAML'
  build-sh-rootfs: |
    IMAGE_FEATURES:remove = "read-only-rootfs"
YAML
        ;;
    overlayfs)
        info "Rootfs mode: overlayfs (tmpfs-backed volatile writable layer)"
        cat >> "$OVERRIDE_FILE" <<'YAML'
  build-sh-rootfs: |
    IMAGE_FEATURES:append = " read-only-rootfs"
    IMAGE_INSTALL:append = " overlayfs-setup"
YAML
        ;;
esac

# ── dm-verity toggle ─────────────────────────────────────────────────────────
if [[ "$DM_VERITY" == "off" ]]; then
    warn "dm-verity: DISABLED — image will NOT be integrity-protected"
    cat >> "$OVERRIDE_FILE" <<'YAML'
  build-sh-verity: |
    INHERIT:remove = "dm-verity-img"
    DM_VERITY_IMAGE = ""
YAML
else
    info "dm-verity: enabled (RSA-3K signed)"
fi

# ── Target override ──────────────────────────────────────────────────────────
if [[ -n "$TARGET" ]]; then
    cat >> "$OVERRIDE_FILE" <<YAML
target:
  - ${TARGET}
YAML
    info "Target override: ${TARGET}"
fi

# ── Build command assembly ───────────────────────────────────────────────────
KAS_CMD=(kas build "${KAS_BASE}:${OVERRIDE_FILE}")
if [[ ${#EXTRA_KAS_ARGS[@]} -gt 0 ]]; then
    KAS_CMD=("kas" "${EXTRA_KAS_ARGS[@]}" "${KAS_BASE}:${OVERRIDE_FILE}")
fi

# Wrap with taskset if CPU affinity is specified
if [[ -n "$CPU_AFFINITY" ]]; then
    command -v taskset >/dev/null 2>&1 || die "taskset not found. Install: apt install util-linux"
    info "CPU affinity: taskset -c ${CPU_AFFINITY}"
    KAS_CMD=(taskset -c "$CPU_AFFINITY" "${KAS_CMD[@]}")
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
info "┌─────────────────────────────────────────────┐"
info "│  Jetson Orin Nano — Hardened BSP Build       │"
info "├─────────────────────────────────────────────┤"
info "│  Cores:      ${CORES} / ${TOTAL_CORES}"
info "│  Affinity:   ${CPU_AFFINITY:-none (all cores)}"
info "│  Rootfs:     ${ROOTFS_MODE}"
info "│  dm-verity:  ${DM_VERITY}"
info "│  Target:     ${TARGET:-<from kas-project.yml>}"
info "│  Override:   ${OVERRIDE_FILE}"
info "└─────────────────────────────────────────────┘"
echo ""

# ── Execute ──────────────────────────────────────────────────────────────────
info "Executing: ${KAS_CMD[*]}"
exec "${KAS_CMD[@]}"
